// System templates to seed on startup
export const SYSTEM_TEMPLATES = [
  {
    name: 'Image Series',
    description: 'Generate a series of related images from a concept prompt using LLM expansion',
    category: 'images',
    version: 1,
    edgeStyle: 'smoothstep',
    nodes: [
      {
        id: 'prompt-1',
        type: 'prompt',
        position: { x: 50, y: 200 },
        data: {
          label: 'Concept',
          status: 'idle',
          prompt:
            'Create 3 variations of a futuristic city at sunset. Each should show different architectural styles but maintain a cohesive color palette.',
          variables: {},
        },
      },
      {
        id: 'llm-1',
        type: 'llm',
        position: { x: 350, y: 200 },
        data: {
          label: 'Prompt Expander',
          status: 'idle',
          inputPrompt: null,
          outputText: null,
          systemPrompt:
            "You are a creative prompt engineer. Take the user's concept and expand it into 3 detailed, specific image generation prompts. Format each prompt on a new line starting with '1.', '2.', '3.'",
          temperature: 0.8,
          maxTokens: 1024,
          topP: 0.9,
          jobId: null,
        },
      },
      {
        id: 'imageGen-1',
        type: 'imageGen',
        position: { x: 700, y: 50 },
        data: {
          label: 'Image 1',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '16:9',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'imageGen-2',
        type: 'imageGen',
        position: { x: 700, y: 250 },
        data: {
          label: 'Image 2',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '16:9',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'imageGen-3',
        type: 'imageGen',
        position: { x: 700, y: 450 },
        data: {
          label: 'Image 3',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '16:9',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'output-1',
        type: 'output',
        position: { x: 1050, y: 250 },
        data: {
          label: 'Final Output',
          status: 'idle',
          inputMedia: null,
          inputType: null,
          outputName: 'image-series',
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'prompt-1',
        target: 'llm-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e2',
        source: 'llm-1',
        target: 'imageGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e3',
        source: 'llm-1',
        target: 'imageGen-2',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e4',
        source: 'llm-1',
        target: 'imageGen-3',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e5',
        source: 'imageGen-2',
        target: 'output-1',
        sourceHandle: 'image',
        targetHandle: 'media',
      },
    ],
  },
  {
    name: 'Image to Video',
    description: 'Create interpolated video between two images with easing animation',
    category: 'video',
    version: 1,
    edgeStyle: 'smoothstep',
    nodes: [
      {
        id: 'image-1',
        type: 'imageInput',
        position: { x: 50, y: 100 },
        data: {
          label: 'Starting Frame',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'image-2',
        type: 'imageInput',
        position: { x: 50, y: 350 },
        data: {
          label: 'Ending Frame',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'prompt-1',
        type: 'prompt',
        position: { x: 50, y: 550 },
        data: {
          label: 'Motion Description',
          status: 'idle',
          prompt: 'Smooth cinematic transition with subtle camera movement',
          variables: {},
        },
      },
      {
        id: 'videoGen-1',
        type: 'videoGen',
        position: { x: 400, y: 200 },
        data: {
          label: 'Video Generator',
          status: 'idle',
          inputImage: null,
          lastFrame: null,
          referenceImages: [],
          inputPrompt: null,
          negativePrompt: 'blurry, distorted, artifacts',
          outputVideo: null,
          model: 'veo-3.1-fast',
          duration: 8,
          aspectRatio: '16:9',
          resolution: '1080p',
          generateAudio: false,
          jobId: null,
        },
      },
      {
        id: 'animation-1',
        type: 'animation',
        position: { x: 750, y: 200 },
        data: {
          label: 'Ease Animation',
          status: 'idle',
          inputVideo: null,
          outputVideo: null,
          curveType: 'preset',
          preset: 'easeInOutCubic',
          customCurve: [0.645, 0.045, 0.355, 1],
          speedMultiplier: 1,
        },
      },
      {
        id: 'output-1',
        type: 'output',
        position: { x: 1100, y: 200 },
        data: {
          label: 'Final Video',
          status: 'idle',
          inputMedia: null,
          inputType: 'video',
          outputName: 'image-to-video',
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'image-1',
        target: 'videoGen-1',
        sourceHandle: 'image',
        targetHandle: 'image',
      },
      {
        id: 'e2',
        source: 'image-2',
        target: 'videoGen-1',
        sourceHandle: 'image',
        targetHandle: 'lastFrame',
      },
      {
        id: 'e3',
        source: 'prompt-1',
        target: 'videoGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e4',
        source: 'videoGen-1',
        target: 'animation-1',
        sourceHandle: 'video',
        targetHandle: 'video',
      },
      {
        id: 'e5',
        source: 'animation-1',
        target: 'output-1',
        sourceHandle: 'video',
        targetHandle: 'media',
      },
    ],
  },
  {
    name: 'Full Content Pipeline',
    description: 'Complete workflow: concept → images → videos → animation → stitched output',
    category: 'full-pipeline',
    version: 1,
    edgeStyle: 'smoothstep',
    nodes: [
      {
        id: 'concept',
        type: 'prompt',
        position: { x: 50, y: 300 },
        data: {
          label: 'Concept',
          status: 'idle',
          prompt:
            'Create a 3-scene story about a robot discovering nature for the first time. Scene 1: Robot in city. Scene 2: Robot enters forest. Scene 3: Robot watches sunset.',
          variables: {},
        },
      },
      {
        id: 'llm-story',
        type: 'llm',
        position: { x: 350, y: 300 },
        data: {
          label: 'Story Expander',
          status: 'idle',
          inputPrompt: null,
          outputText: null,
          systemPrompt:
            'Expand the concept into 3 detailed visual prompts. For each scene, include: setting, lighting, mood, camera angle, and specific details. Number each 1., 2., 3.',
          temperature: 0.8,
          maxTokens: 2048,
          topP: 0.9,
          jobId: null,
        },
      },
      {
        id: 'imageGen-1',
        type: 'imageGen',
        position: { x: 700, y: 100 },
        data: {
          label: 'Scene 1 Image',
          status: 'idle',
          model: 'nano-banana-pro',
          aspectRatio: '16:9',
          resolution: '2K',
        },
      },
      {
        id: 'imageGen-2',
        type: 'imageGen',
        position: { x: 700, y: 300 },
        data: {
          label: 'Scene 2 Image',
          status: 'idle',
          model: 'nano-banana-pro',
          aspectRatio: '16:9',
          resolution: '2K',
        },
      },
      {
        id: 'imageGen-3',
        type: 'imageGen',
        position: { x: 700, y: 500 },
        data: {
          label: 'Scene 3 Image',
          status: 'idle',
          model: 'nano-banana-pro',
          aspectRatio: '16:9',
          resolution: '2K',
        },
      },
      {
        id: 'videoGen-1',
        type: 'videoGen',
        position: { x: 1050, y: 150 },
        data: {
          label: 'Scene 1→2 Video',
          status: 'idle',
          model: 'veo-3.1',
          duration: 6,
          generateAudio: true,
        },
      },
      {
        id: 'videoGen-2',
        type: 'videoGen',
        position: { x: 1050, y: 400 },
        data: {
          label: 'Scene 2→3 Video',
          status: 'idle',
          model: 'veo-3.1',
          duration: 6,
          generateAudio: true,
        },
      },
      {
        id: 'animation-1',
        type: 'animation',
        position: { x: 1400, y: 150 },
        data: {
          label: 'Ease Animation 1',
          status: 'idle',
          preset: 'easeInOutCubic',
          speedMultiplier: 1,
        },
      },
      {
        id: 'animation-2',
        type: 'animation',
        position: { x: 1400, y: 400 },
        data: {
          label: 'Ease Animation 2',
          status: 'idle',
          preset: 'easeInOutCubic',
          speedMultiplier: 1,
        },
      },
      {
        id: 'stitch-1',
        type: 'videoStitch',
        position: { x: 1750, y: 275 },
        data: {
          label: 'Video Stitcher',
          status: 'idle',
          transitionType: 'crossfade',
          transitionDuration: 0.5,
          seamlessLoop: true,
        },
      },
      {
        id: 'output-1',
        type: 'output',
        position: { x: 2100, y: 275 },
        data: {
          label: 'Final Video',
          status: 'idle',
          inputType: 'video',
          outputName: 'full-pipeline-output',
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'concept',
        target: 'llm-story',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e2',
        source: 'llm-story',
        target: 'imageGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e3',
        source: 'llm-story',
        target: 'imageGen-2',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e4',
        source: 'llm-story',
        target: 'imageGen-3',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e5',
        source: 'imageGen-1',
        target: 'videoGen-1',
        sourceHandle: 'image',
        targetHandle: 'image',
      },
      {
        id: 'e6',
        source: 'imageGen-2',
        target: 'videoGen-1',
        sourceHandle: 'image',
        targetHandle: 'lastFrame',
      },
      {
        id: 'e7',
        source: 'imageGen-2',
        target: 'videoGen-2',
        sourceHandle: 'image',
        targetHandle: 'image',
      },
      {
        id: 'e8',
        source: 'imageGen-3',
        target: 'videoGen-2',
        sourceHandle: 'image',
        targetHandle: 'lastFrame',
      },
      {
        id: 'e9',
        source: 'llm-story',
        target: 'videoGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e10',
        source: 'llm-story',
        target: 'videoGen-2',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e11',
        source: 'videoGen-1',
        target: 'animation-1',
        sourceHandle: 'video',
        targetHandle: 'video',
      },
      {
        id: 'e12',
        source: 'videoGen-2',
        target: 'animation-2',
        sourceHandle: 'video',
        targetHandle: 'video',
      },
      {
        id: 'e13',
        source: 'animation-1',
        target: 'stitch-1',
        sourceHandle: 'video',
        targetHandle: 'videos',
      },
      {
        id: 'e14',
        source: 'animation-2',
        target: 'stitch-1',
        sourceHandle: 'video',
        targetHandle: 'videos',
      },
      {
        id: 'e15',
        source: 'stitch-1',
        target: 'output-1',
        sourceHandle: 'video',
        targetHandle: 'media',
      },
    ],
  },
];
