// System templates to seed on startup
export const SYSTEM_TEMPLATES = [
  // ============================================
  // MINIMAL DEFAULT WORKFLOWS (Marketplace Core)
  // ============================================
  {
    name: 'Single Image',
    description: 'Generate an AI image from a source image (img2img)',
    category: 'images',
    version: 1,
    edgeStyle: 'smoothstep',
    nodes: [
      {
        id: 'imageInput-1',
        type: 'imageInput',
        position: { x: 50, y: 150 },
        data: {
          label: 'Source Image',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'prompt-1',
        type: 'prompt',
        position: { x: 50, y: 350 },
        data: {
          label: 'Style Prompt',
          status: 'idle',
          prompt: 'A cinematic, detailed version of this image with enhanced lighting',
          variables: {},
        },
      },
      {
        id: 'imageGen-1',
        type: 'imageGen',
        position: { x: 400, y: 200 },
        data: {
          label: 'Image Generator',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '1:1',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'output-1',
        type: 'output',
        position: { x: 750, y: 200 },
        data: {
          label: 'Final Output',
          status: 'idle',
          inputMedia: null,
          inputType: 'image',
          outputName: 'generated-image',
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'imageInput-1',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e2',
        source: 'prompt-1',
        target: 'imageGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e3',
        source: 'imageGen-1',
        target: 'output-1',
        sourceHandle: 'image',
        targetHandle: 'media',
      },
    ],
  },
  {
    name: 'Single Video',
    description: 'Generate an AI video from a source image (img2video)',
    category: 'video',
    version: 1,
    edgeStyle: 'smoothstep',
    nodes: [
      {
        id: 'imageInput-1',
        type: 'imageInput',
        position: { x: 50, y: 150 },
        data: {
          label: 'Starting Frame',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'prompt-1',
        type: 'prompt',
        position: { x: 50, y: 350 },
        data: {
          label: 'Motion Prompt',
          status: 'idle',
          prompt: 'Cinematic slow motion with subtle camera movement',
          variables: {},
        },
      },
      {
        id: 'videoGen-1',
        type: 'videoGen',
        position: { x: 400, y: 200 },
        data: {
          label: 'Video Generator',
          status: 'idle',
          inputImage: null,
          lastFrame: null,
          referenceImages: [],
          inputPrompt: null,
          negativePrompt: 'blurry, distorted, artifacts',
          outputVideo: null,
          model: 'veo-3.1-fast',
          duration: 8,
          aspectRatio: '16:9',
          resolution: '1080p',
          generateAudio: false,
          jobId: null,
        },
      },
      {
        id: 'output-1',
        type: 'output',
        position: { x: 750, y: 200 },
        data: {
          label: 'Final Output',
          status: 'idle',
          inputMedia: null,
          inputType: 'video',
          outputName: 'generated-video',
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'imageInput-1',
        target: 'videoGen-1',
        sourceHandle: 'image',
        targetHandle: 'image',
      },
      {
        id: 'e2',
        source: 'prompt-1',
        target: 'videoGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e3',
        source: 'videoGen-1',
        target: 'output-1',
        sourceHandle: 'video',
        targetHandle: 'media',
      },
    ],
  },
  // ============================================
  // ADVANCED WORKFLOWS
  // ============================================
  {
    name: 'Image Series',
    description: 'Generate a series of related images from a concept prompt using LLM expansion',
    category: 'images',
    version: 1,
    edgeStyle: 'smoothstep',
    nodes: [
      {
        id: 'prompt-1',
        type: 'prompt',
        position: { x: 50, y: 200 },
        data: {
          label: 'Concept',
          status: 'idle',
          prompt:
            'Create 3 variations of a futuristic city at sunset. Each should show different architectural styles but maintain a cohesive color palette.',
          variables: {},
        },
      },
      {
        id: 'llm-1',
        type: 'llm',
        position: { x: 350, y: 200 },
        data: {
          label: 'Prompt Expander',
          status: 'idle',
          inputPrompt: null,
          outputText: null,
          systemPrompt:
            "You are a creative prompt engineer. Take the user's concept and expand it into 3 detailed, specific image generation prompts. Format each prompt on a new line starting with '1.', '2.', '3.'",
          temperature: 0.8,
          maxTokens: 1024,
          topP: 0.9,
          jobId: null,
        },
      },
      {
        id: 'imageGen-1',
        type: 'imageGen',
        position: { x: 700, y: 50 },
        data: {
          label: 'Image 1',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '16:9',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'imageGen-2',
        type: 'imageGen',
        position: { x: 700, y: 250 },
        data: {
          label: 'Image 2',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '16:9',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'imageGen-3',
        type: 'imageGen',
        position: { x: 700, y: 450 },
        data: {
          label: 'Image 3',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '16:9',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'output-1',
        type: 'output',
        position: { x: 1050, y: 250 },
        data: {
          label: 'Final Output',
          status: 'idle',
          inputMedia: null,
          inputType: null,
          outputName: 'image-series',
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'prompt-1',
        target: 'llm-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e2',
        source: 'llm-1',
        target: 'imageGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e3',
        source: 'llm-1',
        target: 'imageGen-2',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e4',
        source: 'llm-1',
        target: 'imageGen-3',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e5',
        source: 'imageGen-2',
        target: 'output-1',
        sourceHandle: 'image',
        targetHandle: 'media',
      },
    ],
  },
  {
    name: 'Image to Video',
    description: 'Create interpolated video between two images with easing animation',
    category: 'video',
    version: 1,
    edgeStyle: 'smoothstep',
    nodes: [
      {
        id: 'image-1',
        type: 'imageInput',
        position: { x: 50, y: 100 },
        data: {
          label: 'Starting Frame',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'image-2',
        type: 'imageInput',
        position: { x: 50, y: 350 },
        data: {
          label: 'Ending Frame',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'prompt-1',
        type: 'prompt',
        position: { x: 50, y: 550 },
        data: {
          label: 'Motion Description',
          status: 'idle',
          prompt: 'Smooth cinematic transition with subtle camera movement',
          variables: {},
        },
      },
      {
        id: 'videoGen-1',
        type: 'videoGen',
        position: { x: 400, y: 200 },
        data: {
          label: 'Video Generator',
          status: 'idle',
          inputImage: null,
          lastFrame: null,
          referenceImages: [],
          inputPrompt: null,
          negativePrompt: 'blurry, distorted, artifacts',
          outputVideo: null,
          model: 'veo-3.1-fast',
          duration: 8,
          aspectRatio: '16:9',
          resolution: '1080p',
          generateAudio: false,
          jobId: null,
        },
      },
      {
        id: 'animation-1',
        type: 'animation',
        position: { x: 750, y: 200 },
        data: {
          label: 'Ease Animation',
          status: 'idle',
          inputVideo: null,
          outputVideo: null,
          curveType: 'preset',
          preset: 'easeInOutCubic',
          customCurve: [0.645, 0.045, 0.355, 1],
          speedMultiplier: 1,
        },
      },
      {
        id: 'output-1',
        type: 'output',
        position: { x: 1100, y: 200 },
        data: {
          label: 'Final Video',
          status: 'idle',
          inputMedia: null,
          inputType: 'video',
          outputName: 'image-to-video',
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'image-1',
        target: 'videoGen-1',
        sourceHandle: 'image',
        targetHandle: 'image',
      },
      {
        id: 'e2',
        source: 'image-2',
        target: 'videoGen-1',
        sourceHandle: 'image',
        targetHandle: 'lastFrame',
      },
      {
        id: 'e3',
        source: 'prompt-1',
        target: 'videoGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e4',
        source: 'videoGen-1',
        target: 'animation-1',
        sourceHandle: 'video',
        targetHandle: 'video',
      },
      {
        id: 'e5',
        source: 'animation-1',
        target: 'output-1',
        sourceHandle: 'video',
        targetHandle: 'media',
      },
    ],
  },
  {
    name: 'Full Content Pipeline',
    description: 'Complete workflow: concept → images → videos → animation → stitched output',
    category: 'full-pipeline',
    version: 1,
    edgeStyle: 'smoothstep',
    nodes: [
      {
        id: 'concept',
        type: 'prompt',
        position: { x: 50, y: 300 },
        data: {
          label: 'Concept',
          status: 'idle',
          prompt:
            'Create a 3-scene story about a robot discovering nature for the first time. Scene 1: Robot in city. Scene 2: Robot enters forest. Scene 3: Robot watches sunset.',
          variables: {},
        },
      },
      {
        id: 'llm-story',
        type: 'llm',
        position: { x: 350, y: 300 },
        data: {
          label: 'Story Expander',
          status: 'idle',
          inputPrompt: null,
          outputText: null,
          systemPrompt:
            'Expand the concept into 3 detailed visual prompts. For each scene, include: setting, lighting, mood, camera angle, and specific details. Number each 1., 2., 3.',
          temperature: 0.8,
          maxTokens: 2048,
          topP: 0.9,
          jobId: null,
        },
      },
      {
        id: 'imageGen-1',
        type: 'imageGen',
        position: { x: 700, y: 100 },
        data: {
          label: 'Scene 1 Image',
          status: 'idle',
          model: 'nano-banana-pro',
          aspectRatio: '16:9',
          resolution: '2K',
        },
      },
      {
        id: 'imageGen-2',
        type: 'imageGen',
        position: { x: 700, y: 300 },
        data: {
          label: 'Scene 2 Image',
          status: 'idle',
          model: 'nano-banana-pro',
          aspectRatio: '16:9',
          resolution: '2K',
        },
      },
      {
        id: 'imageGen-3',
        type: 'imageGen',
        position: { x: 700, y: 500 },
        data: {
          label: 'Scene 3 Image',
          status: 'idle',
          model: 'nano-banana-pro',
          aspectRatio: '16:9',
          resolution: '2K',
        },
      },
      {
        id: 'videoGen-1',
        type: 'videoGen',
        position: { x: 1050, y: 150 },
        data: {
          label: 'Scene 1→2 Video',
          status: 'idle',
          model: 'veo-3.1',
          duration: 6,
          generateAudio: true,
        },
      },
      {
        id: 'videoGen-2',
        type: 'videoGen',
        position: { x: 1050, y: 400 },
        data: {
          label: 'Scene 2→3 Video',
          status: 'idle',
          model: 'veo-3.1',
          duration: 6,
          generateAudio: true,
        },
      },
      {
        id: 'animation-1',
        type: 'animation',
        position: { x: 1400, y: 150 },
        data: {
          label: 'Ease Animation 1',
          status: 'idle',
          preset: 'easeInOutCubic',
          speedMultiplier: 1,
        },
      },
      {
        id: 'animation-2',
        type: 'animation',
        position: { x: 1400, y: 400 },
        data: {
          label: 'Ease Animation 2',
          status: 'idle',
          preset: 'easeInOutCubic',
          speedMultiplier: 1,
        },
      },
      {
        id: 'stitch-1',
        type: 'videoStitch',
        position: { x: 1750, y: 275 },
        data: {
          label: 'Video Stitcher',
          status: 'idle',
          transitionType: 'crossfade',
          transitionDuration: 0.5,
          seamlessLoop: true,
        },
      },
      {
        id: 'output-1',
        type: 'output',
        position: { x: 2100, y: 275 },
        data: {
          label: 'Final Video',
          status: 'idle',
          inputType: 'video',
          outputName: 'full-pipeline-output',
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'concept',
        target: 'llm-story',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e2',
        source: 'llm-story',
        target: 'imageGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e3',
        source: 'llm-story',
        target: 'imageGen-2',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e4',
        source: 'llm-story',
        target: 'imageGen-3',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e5',
        source: 'imageGen-1',
        target: 'videoGen-1',
        sourceHandle: 'image',
        targetHandle: 'image',
      },
      {
        id: 'e6',
        source: 'imageGen-2',
        target: 'videoGen-1',
        sourceHandle: 'image',
        targetHandle: 'lastFrame',
      },
      {
        id: 'e7',
        source: 'imageGen-2',
        target: 'videoGen-2',
        sourceHandle: 'image',
        targetHandle: 'image',
      },
      {
        id: 'e8',
        source: 'imageGen-3',
        target: 'videoGen-2',
        sourceHandle: 'image',
        targetHandle: 'lastFrame',
      },
      {
        id: 'e9',
        source: 'llm-story',
        target: 'videoGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e10',
        source: 'llm-story',
        target: 'videoGen-2',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e11',
        source: 'videoGen-1',
        target: 'animation-1',
        sourceHandle: 'video',
        targetHandle: 'video',
      },
      {
        id: 'e12',
        source: 'videoGen-2',
        target: 'animation-2',
        sourceHandle: 'video',
        targetHandle: 'video',
      },
      {
        id: 'e13',
        source: 'animation-1',
        target: 'stitch-1',
        sourceHandle: 'video',
        targetHandle: 'videos',
      },
      {
        id: 'e14',
        source: 'animation-2',
        target: 'stitch-1',
        sourceHandle: 'video',
        targetHandle: 'videos',
      },
      {
        id: 'e15',
        source: 'stitch-1',
        target: 'output-1',
        sourceHandle: 'video',
        targetHandle: 'media',
      },
    ],
  },
  // ============================================
  // NODE-BANANA IMPORTED WORKFLOWS
  // ============================================
  {
    name: 'Product Shot',
    description: 'Place a product in a new scene or environment for e-commerce visualization',
    category: 'images',
    version: 1,
    edgeStyle: 'smoothstep',
    nodes: [
      {
        id: 'imageInput-1',
        type: 'imageInput',
        position: { x: 50, y: 100 },
        data: {
          label: 'Product Image',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'imageInput-2',
        type: 'imageInput',
        position: { x: 50, y: 350 },
        data: {
          label: 'Scene Reference',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'prompt-1',
        type: 'prompt',
        position: { x: 50, y: 550 },
        data: {
          label: 'Composition Prompt',
          status: 'idle',
          prompt: 'Place the product naturally in the scene with realistic lighting and shadows',
          variables: {},
        },
      },
      {
        id: 'imageGen-1',
        type: 'imageGen',
        position: { x: 400, y: 250 },
        data: {
          label: 'Generate Composite',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '1:1',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'output-1',
        type: 'output',
        position: { x: 750, y: 250 },
        data: {
          label: 'Final Output',
          status: 'idle',
          inputMedia: null,
          inputType: 'image',
          outputName: 'product-shot',
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'imageInput-1',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e2',
        source: 'imageInput-2',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e3',
        source: 'prompt-1',
        target: 'imageGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e4',
        source: 'imageGen-1',
        target: 'output-1',
        sourceHandle: 'image',
        targetHandle: 'media',
      },
    ],
  },
  {
    name: 'Model + Product',
    description:
      'Combine a model with a product and custom background for fashion/lifestyle photography',
    category: 'images',
    version: 1,
    edgeStyle: 'smoothstep',
    nodes: [
      {
        id: 'imageInput-1',
        type: 'imageInput',
        position: { x: 50, y: 50 },
        data: {
          label: 'Model Image',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'imageInput-2',
        type: 'imageInput',
        position: { x: 50, y: 250 },
        data: {
          label: 'Product Image',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'imageInput-3',
        type: 'imageInput',
        position: { x: 50, y: 450 },
        data: {
          label: 'Background Reference',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'prompt-1',
        type: 'prompt',
        position: { x: 50, y: 650 },
        data: {
          label: 'Style Prompt',
          status: 'idle',
          prompt:
            'Fashion editorial photo of model wearing/holding the product with professional studio lighting',
          variables: {},
        },
      },
      {
        id: 'imageGen-1',
        type: 'imageGen',
        position: { x: 400, y: 300 },
        data: {
          label: 'Generate Composite',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '4:5',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'output-1',
        type: 'output',
        position: { x: 750, y: 300 },
        data: {
          label: 'Final Output',
          status: 'idle',
          inputMedia: null,
          inputType: 'image',
          outputName: 'model-product-shot',
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'imageInput-1',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e2',
        source: 'imageInput-2',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e3',
        source: 'imageInput-3',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e4',
        source: 'prompt-1',
        target: 'imageGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e5',
        source: 'imageGen-1',
        target: 'output-1',
        sourceHandle: 'image',
        targetHandle: 'media',
      },
    ],
  },
  {
    name: 'Color Variations',
    description:
      'Generate product color variants using reference palettes for product line mockups',
    category: 'images',
    version: 1,
    edgeStyle: 'smoothstep',
    nodes: [
      {
        id: 'imageInput-1',
        type: 'imageInput',
        position: { x: 50, y: 50 },
        data: {
          label: 'Product Image',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'imageInput-2',
        type: 'imageInput',
        position: { x: 50, y: 250 },
        data: {
          label: 'Color Palette 1',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'imageInput-3',
        type: 'imageInput',
        position: { x: 50, y: 450 },
        data: {
          label: 'Color Palette 2',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'prompt-1',
        type: 'prompt',
        position: { x: 50, y: 650 },
        data: {
          label: 'Variation Prompt',
          status: 'idle',
          prompt:
            'Generate product color variations matching the provided color palettes while preserving product details and shape',
          variables: {},
        },
      },
      {
        id: 'imageGen-1',
        type: 'imageGen',
        position: { x: 400, y: 300 },
        data: {
          label: 'Generate Variations',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '1:1',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'output-1',
        type: 'output',
        position: { x: 750, y: 300 },
        data: {
          label: 'Final Output',
          status: 'idle',
          inputMedia: null,
          inputType: 'image',
          outputName: 'color-variations',
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'imageInput-1',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e2',
        source: 'imageInput-2',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e3',
        source: 'imageInput-3',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e4',
        source: 'prompt-1',
        target: 'imageGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e5',
        source: 'imageGen-1',
        target: 'output-1',
        sourceHandle: 'image',
        targetHandle: 'media',
      },
    ],
  },
  {
    name: 'Background Swap',
    description: 'Replace the background of a subject with a new environment',
    category: 'images',
    version: 1,
    edgeStyle: 'smoothstep',
    nodes: [
      {
        id: 'imageInput-1',
        type: 'imageInput',
        position: { x: 50, y: 100 },
        data: {
          label: 'Subject Image',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'imageInput-2',
        type: 'imageInput',
        position: { x: 50, y: 350 },
        data: {
          label: 'New Background',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'prompt-1',
        type: 'prompt',
        position: { x: 50, y: 550 },
        data: {
          label: 'Composition Prompt',
          status: 'idle',
          prompt:
            'Seamlessly place the subject in the new background with matching lighting and perspective',
          variables: {},
        },
      },
      {
        id: 'imageGen-1',
        type: 'imageGen',
        position: { x: 400, y: 250 },
        data: {
          label: 'Generate Composite',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '16:9',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'output-1',
        type: 'output',
        position: { x: 750, y: 250 },
        data: {
          label: 'Final Output',
          status: 'idle',
          inputMedia: null,
          inputType: 'image',
          outputName: 'background-swap',
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'imageInput-1',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e2',
        source: 'imageInput-2',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e3',
        source: 'prompt-1',
        target: 'imageGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e4',
        source: 'imageGen-1',
        target: 'output-1',
        sourceHandle: 'image',
        targetHandle: 'media',
      },
    ],
  },
  {
    name: 'Style Transfer',
    description: 'Apply visual style from a reference image to your content',
    category: 'images',
    version: 1,
    edgeStyle: 'smoothstep',
    nodes: [
      {
        id: 'imageInput-1',
        type: 'imageInput',
        position: { x: 50, y: 100 },
        data: {
          label: 'Style Reference',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'imageInput-2',
        type: 'imageInput',
        position: { x: 50, y: 350 },
        data: {
          label: 'Content Image',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'prompt-1',
        type: 'prompt',
        position: { x: 50, y: 550 },
        data: {
          label: 'Style Prompt',
          status: 'idle',
          prompt:
            'Apply the artistic style, color palette, and visual aesthetics from the reference to the content image',
          variables: {},
        },
      },
      {
        id: 'imageGen-1',
        type: 'imageGen',
        position: { x: 400, y: 250 },
        data: {
          label: 'Generate Styled',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '1:1',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'output-1',
        type: 'output',
        position: { x: 750, y: 250 },
        data: {
          label: 'Final Output',
          status: 'idle',
          inputMedia: null,
          inputType: 'image',
          outputName: 'style-transfer',
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'imageInput-1',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e2',
        source: 'imageInput-2',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e3',
        source: 'prompt-1',
        target: 'imageGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e4',
        source: 'imageGen-1',
        target: 'output-1',
        sourceHandle: 'image',
        targetHandle: 'media',
      },
    ],
  },
  {
    name: 'Scene Composite',
    description:
      'Combine multiple elements into a cohesive scene for environmental design and mood boards',
    category: 'images',
    version: 1,
    edgeStyle: 'smoothstep',
    nodes: [
      {
        id: 'imageInput-1',
        type: 'imageInput',
        position: { x: 50, y: 50 },
        data: {
          label: 'Element 1',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'imageInput-2',
        type: 'imageInput',
        position: { x: 50, y: 250 },
        data: {
          label: 'Element 2',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'imageInput-3',
        type: 'imageInput',
        position: { x: 50, y: 450 },
        data: {
          label: 'Element 3',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'prompt-1',
        type: 'prompt',
        position: { x: 50, y: 650 },
        data: {
          label: 'Scene Prompt',
          status: 'idle',
          prompt:
            'Combine all elements into a cohesive scene with unified lighting, consistent perspective, and harmonious composition',
          variables: {},
        },
      },
      {
        id: 'imageGen-1',
        type: 'imageGen',
        position: { x: 400, y: 300 },
        data: {
          label: 'Generate Scene',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '16:9',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'output-1',
        type: 'output',
        position: { x: 750, y: 300 },
        data: {
          label: 'Final Output',
          status: 'idle',
          inputMedia: null,
          inputType: 'image',
          outputName: 'scene-composite',
        },
      },
    ],
    edges: [
      {
        id: 'e1',
        source: 'imageInput-1',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e2',
        source: 'imageInput-2',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e3',
        source: 'imageInput-3',
        target: 'imageGen-1',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'e4',
        source: 'prompt-1',
        target: 'imageGen-1',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'e5',
        source: 'imageGen-1',
        target: 'output-1',
        sourceHandle: 'image',
        targetHandle: 'media',
      },
    ],
  },
  {
    name: 'Moodboard Generator',
    description:
      'Generate 4 mood-consistent images from reference images and a base prompt. The LLM creates variations while maintaining the overall aesthetic.',
    category: 'images',
    version: 1,
    edgeStyle: 'bezier',
    nodes: [
      {
        id: 'node_1',
        type: 'imageInput',
        position: { x: 0, y: 0 },
        data: {
          label: 'Mood Reference 1',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'node_2',
        type: 'imageInput',
        position: { x: 0, y: 150 },
        data: {
          label: 'Mood Reference 2',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'node_3',
        type: 'imageInput',
        position: { x: 0, y: 300 },
        data: {
          label: 'Mood Reference 3',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'node_4',
        type: 'imageInput',
        position: { x: 0, y: 450 },
        data: {
          label: 'Mood Reference 4',
          status: 'idle',
          image: null,
          filename: null,
          dimensions: null,
          source: 'upload',
        },
      },
      {
        id: 'node_5',
        type: 'prompt',
        position: { x: 0, y: 600 },
        data: {
          label: 'Base Concept',
          status: 'idle',
          prompt: 'A serene workspace with natural light, minimalist furniture, and plants',
          variables: {},
        },
      },
      {
        id: 'node_6',
        type: 'llm',
        position: { x: 300, y: 525 },
        data: {
          label: 'Prompt Expander',
          status: 'idle',
          inputPrompt: null,
          outputText: null,
          systemPrompt:
            "You are a creative director creating a moodboard. Given a base concept, generate exactly 4 distinct image prompts that explore different angles of the same mood/aesthetic. Each prompt should:\n1. Maintain the core mood and style\n2. Explore a unique composition or perspective\n3. Be detailed enough for AI image generation\n4. Reference the visual style from the mood images\n\nOutput format: Return ONLY 4 prompts separated by '|||' (no numbering, no extra text).\n\nExample output:\nA cozy reading nook with warm afternoon light filtering through sheer curtains, stack of vintage books|||A minimalist desk setup with a single monstera plant, soft shadows|||Morning coffee scene with steam rising, natural wood textures|||Evening workspace with warm lamp glow, organized stationery",
          temperature: 0.8,
          maxTokens: 1024,
          topP: 0.9,
          jobId: null,
        },
      },
      {
        id: 'node_7',
        type: 'imageGen',
        position: { x: 600, y: 0 },
        data: {
          label: 'Moodboard Image 1',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '1:1',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'node_8',
        type: 'imageGen',
        position: { x: 600, y: 200 },
        data: {
          label: 'Moodboard Image 2',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '1:1',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'node_9',
        type: 'imageGen',
        position: { x: 600, y: 400 },
        data: {
          label: 'Moodboard Image 3',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '1:1',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'node_10',
        type: 'imageGen',
        position: { x: 600, y: 600 },
        data: {
          label: 'Moodboard Image 4',
          status: 'idle',
          inputImages: [],
          inputPrompt: null,
          outputImage: null,
          model: 'nano-banana-pro',
          aspectRatio: '1:1',
          resolution: '2K',
          outputFormat: 'jpg',
          jobId: null,
        },
      },
      {
        id: 'node_11',
        type: 'output',
        position: { x: 900, y: 0 },
        data: {
          label: 'Output 1',
          status: 'idle',
          inputMedia: null,
          inputType: null,
          outputName: 'moodboard_1',
        },
      },
      {
        id: 'node_12',
        type: 'output',
        position: { x: 900, y: 200 },
        data: {
          label: 'Output 2',
          status: 'idle',
          inputMedia: null,
          inputType: null,
          outputName: 'moodboard_2',
        },
      },
      {
        id: 'node_13',
        type: 'output',
        position: { x: 900, y: 400 },
        data: {
          label: 'Output 3',
          status: 'idle',
          inputMedia: null,
          inputType: null,
          outputName: 'moodboard_3',
        },
      },
      {
        id: 'node_14',
        type: 'output',
        position: { x: 900, y: 600 },
        data: {
          label: 'Output 4',
          status: 'idle',
          inputMedia: null,
          inputType: null,
          outputName: 'moodboard_4',
        },
      },
    ],
    edges: [
      // All 4 mood reference images connect to all 4 ImageGen nodes
      {
        id: 'edge_node_1_node_7',
        source: 'node_1',
        target: 'node_7',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'edge_node_2_node_7',
        source: 'node_2',
        target: 'node_7',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'edge_node_3_node_7',
        source: 'node_3',
        target: 'node_7',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'edge_node_4_node_7',
        source: 'node_4',
        target: 'node_7',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'edge_node_1_node_8',
        source: 'node_1',
        target: 'node_8',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'edge_node_2_node_8',
        source: 'node_2',
        target: 'node_8',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'edge_node_3_node_8',
        source: 'node_3',
        target: 'node_8',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'edge_node_4_node_8',
        source: 'node_4',
        target: 'node_8',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'edge_node_1_node_9',
        source: 'node_1',
        target: 'node_9',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'edge_node_2_node_9',
        source: 'node_2',
        target: 'node_9',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'edge_node_3_node_9',
        source: 'node_3',
        target: 'node_9',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'edge_node_4_node_9',
        source: 'node_4',
        target: 'node_9',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'edge_node_1_node_10',
        source: 'node_1',
        target: 'node_10',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'edge_node_2_node_10',
        source: 'node_2',
        target: 'node_10',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'edge_node_3_node_10',
        source: 'node_3',
        target: 'node_10',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      {
        id: 'edge_node_4_node_10',
        source: 'node_4',
        target: 'node_10',
        sourceHandle: 'image',
        targetHandle: 'images',
      },
      // Prompt to LLM
      {
        id: 'edge_node_5_node_6',
        source: 'node_5',
        target: 'node_6',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      // LLM to all 4 ImageGen nodes
      {
        id: 'edge_node_6_node_7',
        source: 'node_6',
        target: 'node_7',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'edge_node_6_node_8',
        source: 'node_6',
        target: 'node_8',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'edge_node_6_node_9',
        source: 'node_6',
        target: 'node_9',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      {
        id: 'edge_node_6_node_10',
        source: 'node_6',
        target: 'node_10',
        sourceHandle: 'text',
        targetHandle: 'prompt',
      },
      // ImageGen to Output connections
      {
        id: 'edge_node_7_node_11',
        source: 'node_7',
        target: 'node_11',
        sourceHandle: 'image',
        targetHandle: 'media',
      },
      {
        id: 'edge_node_8_node_12',
        source: 'node_8',
        target: 'node_12',
        sourceHandle: 'image',
        targetHandle: 'media',
      },
      {
        id: 'edge_node_9_node_13',
        source: 'node_9',
        target: 'node_13',
        sourceHandle: 'image',
        targetHandle: 'media',
      },
      {
        id: 'edge_node_10_node_14',
        source: 'node_10',
        target: 'node_14',
        sourceHandle: 'image',
        targetHandle: 'media',
      },
    ],
  },
];
